// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package RAE

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RAEStreamServiceClient is the client API for RAEStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RAEStreamServiceClient interface {
	FetchResponse(ctx context.Context, in *Request, opts ...grpc.CallOption) (RAEStreamService_FetchResponseClient, error)
}

type rAEStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRAEStreamServiceClient(cc grpc.ClientConnInterface) RAEStreamServiceClient {
	return &rAEStreamServiceClient{cc}
}

func (c *rAEStreamServiceClient) FetchResponse(ctx context.Context, in *Request, opts ...grpc.CallOption) (RAEStreamService_FetchResponseClient, error) {
	stream, err := c.cc.NewStream(ctx, &RAEStreamService_ServiceDesc.Streams[0], "/protobuf.RAEStreamService/FetchResponse", opts...)
	if err != nil {
		return nil, err
	}
	x := &rAEStreamServiceFetchResponseClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RAEStreamService_FetchResponseClient interface {
	Recv() (*Response, error)
	grpc.ClientStream
}

type rAEStreamServiceFetchResponseClient struct {
	grpc.ClientStream
}

func (x *rAEStreamServiceFetchResponseClient) Recv() (*Response, error) {
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RAEStreamServiceServer is the server API for RAEStreamService service.
// All implementations must embed UnimplementedRAEStreamServiceServer
// for forward compatibility
type RAEStreamServiceServer interface {
	FetchResponse(*Request, RAEStreamService_FetchResponseServer) error
	mustEmbedUnimplementedRAEStreamServiceServer()
}

// UnimplementedRAEStreamServiceServer must be embedded to have forward compatible implementations.
type UnimplementedRAEStreamServiceServer struct {
}

func (UnimplementedRAEStreamServiceServer) FetchResponse(*Request, RAEStreamService_FetchResponseServer) error {
	return status.Errorf(codes.Unimplemented, "method FetchResponse not implemented")
}
func (UnimplementedRAEStreamServiceServer) mustEmbedUnimplementedRAEStreamServiceServer() {}

// UnsafeRAEStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RAEStreamServiceServer will
// result in compilation errors.
type UnsafeRAEStreamServiceServer interface {
	mustEmbedUnimplementedRAEStreamServiceServer()
}

func RegisterRAEStreamServiceServer(s grpc.ServiceRegistrar, srv RAEStreamServiceServer) {
	s.RegisterService(&RAEStreamService_ServiceDesc, srv)
}

func _RAEStreamService_FetchResponse_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Request)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RAEStreamServiceServer).FetchResponse(m, &rAEStreamServiceFetchResponseServer{stream})
}

type RAEStreamService_FetchResponseServer interface {
	Send(*Response) error
	grpc.ServerStream
}

type rAEStreamServiceFetchResponseServer struct {
	grpc.ServerStream
}

func (x *rAEStreamServiceFetchResponseServer) Send(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

// RAEStreamService_ServiceDesc is the grpc.ServiceDesc for RAEStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RAEStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.RAEStreamService",
	HandlerType: (*RAEStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FetchResponse",
			Handler:       _RAEStreamService_FetchResponse_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rpc/RAE.proto",
}
